services:
  api:
    build: .
    container_name: app  # Set the container name to "app"
    restart: always  # Automatically restart the container
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis  # Set the container name to "redis"
    restart: always  # Automatically restart the container
    networks:
      - app-network

networks:
  app-network:
    driver: bridge