services:
  # Our Earthquake API service
  api:
    build: .  # Builds from our Dockerfile
    container_name: earthquake-api
    ports:
      - "8000:8000"  # Maps container port to host port
    environment:
      - REDIS_HOST=redis  # Points to the Redis service name
      - REDIS_PORT=6379  # Default Redis port
    depends_on:
      - redis  # Ensures Redis starts first
  
  # Redis service for caching
  redis:
    image: redis:latest  # Using latest Redis image
    container_name: earthquake-redis
    ports:
      - "6379:6379"  # Maps Redis port to host